[unstable]
build-std = [
	"core",
	"compiler_builtins",
]
#build-std-features = ["stdsimd"]
#build-std-features = ["compiler-builtins-mem"]

[build]
target = "arcv2-none-elf32"
#rustflags = ["--emit=obj"]
#rustflags = ["--emit=llvm-ir"]
#rustflags = ["--emit=llvm-ir", "--emit=obj"]
#rustflags = ["--emit=llvm-ir", "-o", "rust_main.ll"]
